const items = {
  "10 Karat Gold": { rp: 1, money: 300, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/07/Icon-10-karat-gold.png" },
  "12 Karat Gold": { rp: 1, money: 500, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/e7/Icon-12-karat-gold.png" },
  "16x Microchip": { rp: 1, money: 17600, type: "item", icon: "undefined" },
  "18 Karat Gold": { rp: 1, money: 800, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/8e/Icon-18-karat-gold.png" },
  "24 Karat Gold": { rp: 1, money: 1200, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f6/Icon-24-karat-gold.png" },
  "2x Microchip": { rp: 1, money: 4000, type: "item", icon: "undefined" },
  "2x64x Microchip": { rp: 1, money: 100000, type: "item", icon: "undefined" },
  "32x Microchip": { rp: 1, money: 22000, type: "item", icon: "undefined" },
  "3x64x Microchip": { rp: 1, money: 250000, type: "item", icon: "undefined" },
  "4x Microchip": { rp: 1, money: 8400, type: "item", icon: "undefined" },
  "4x64x Microchip": { rp: 100, money: 375000, type: "item", icon: "undefined" },
  "5x64x Microchip": { rp: 150, money: 1000000, type: "item", icon: "undefined" },
  "64x Microchip": { rp: 1, money: 26400, type: "item", icon: "undefined" },
  "6x64x Microchip": { rp: 200, money: 2000000, type: "item", icon: "undefined" },
  "7x64x Microchip": { rp: 250, money: 3000000, type: "item", icon: "undefined" },
  "8 Karat Gold": { rp: 1, money: 160, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/40/Icon-8-karat-gold.png" },
  "8x Microchip": { rp: 1, money: 13200, type: "item", icon: "undefined" },
  "8x64x Microchip": { rp: 300, money: 5000000, type: "item", icon: "undefined" },
  "Acetic Acid": { rp: 7, money: 14.5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/6/6c/Icon-acetic-acid.png" },
  "Aggregate": { rp: 1, money: 14.59, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/e5/Icon-aggregate.png" },
  "Alumina": { rp: 1, money: 100, type: "item", icon: "http://static.wikitide.net/industrialistwiki/c/cf/Icon-alumina.png" },
  "Alumina Dust": { rp: 1, money: 90, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/aa/Icon-alumina-dust.png" },
  "Aluminium Ingot": { rp: 65, money: 800, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b0/Icon-aluminium-ingot.png" },
  "Ammonia": { rp: 15, money: 1, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/8/82/Icon-ammonia.png" },
  "Argon": { rp: 0, money: 2, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/4/4f/Icon-argon.png" },
  "Bauxite Residue": { rp: 1, money: 50, type: "item", icon: "http://static.wikitide.net/industrialistwiki/6/61/Icon-bauxite-residue.png" },
  "Black Dye": { rp: 1, money: 8.7, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/d7/Icon-black-dye.png" },
  "Boric Acid": { rp: 12, money: 1500, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/4/4b/Icon-boric-acid.png" },
  "Boron": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/82/Icon-boron.png" },
  "Brass Ingot": { rp: 35, money: 80, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/48/Icon-brass-ingot.png" },
  "Brick": { rp: 2, money: 50, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/0b/Icon-brick.png" },
  "Cat": { rp: 1, money: 20000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/c/cf/Icon-cat.png" },
  "Cement": { rp: 1, money: 30, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/de/Icon-cement.png" },
  "Chair": { rp: 30, money: 1029.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/44/Icon-chair.png" },
  "Charged Lithium-Ion Battery": { rp: 1, money: 4000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/51/Icon-charged-lithium-ion-battery.png" },
  "Cheap Water Bottle": { rp: 5, money: 130.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/0e/Icon-cheap-water-bottle.png" },
  "Chlorine": { rp: 0.5, money: 0.2, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/1/11/Icon-chlorine.png" },
  "Chunk PLank": { rp: 1, money: 3.48, type: "item", icon: "undefined" },
  "Clay": { rp: 0.2, money: 13, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fc/Icon-clay.png" },
  "Clay Brick": { rp: 1, money: 28, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/a4/Icon-clay-brick.png" },
  "Coal": { rp: 1, money: 5.22, type: "item", icon: "http://static.wikitide.net/industrialistwiki/2/2d/Icon-coal.png" },
  "Coke Fuel": { rp: 9, money: 18, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fd/Icon-coke-fuel.png" },
  "Concentrated Salt Solution": { rp: 1, money: 2, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/8/8d/Icon-concentrated-salt-solution.png" },
  "Concrete Block": { rp: 1, money: 150, type: "item", icon: "http://static.wikitide.net/industrialistwiki/3/32/Icon-concrete-block.png" },
  "Condensate": { rp: 0, money: 0.1, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/3/36/Icon-condensate.png" },
  "Contaminated Water": { rp: 0, money: -241, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/1/1c/Icon-contaminated-water.png" },
  "Control Rod": { rp: 1, money: 150000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/77/Icon-control-rod.png" },
  "Copper Drill Head": { rp: 25, money: 20000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/98/Icon-copper-drill-head.png" },
  "Copper Ingot": { rp: 1.5, money: 26.68, type: "item", icon: "http://static.wikitide.net/industrialistwiki/6/60/Icon-copper-ingot.png" },
  "Copper Mix": { rp: 1, money: 3, type: "item", icon: "http://static.wikitide.net/industrialistwiki/3/36/Icon-copper-mix.png" },
  "Copper Plate": { rp: 6, money: 32.86, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b3/Icon-copper-plate.png" },
  "Copper Powder": { rp: 1, money: 7, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/1c/Icon-copper-powder.png" },
  "Copper Wire": { rp: 1, money: 7.31, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/78/Icon-copper-wire.png" },
  "Crankshaft": { rp: 35, money: 754, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/ef/Icon-crankshaft.png" },
  "Crude Diesel": { rp: 1, money: 13.05, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/0/03/Icon-crude-diesel.png" },
  "Crude Oil": { rp: 0.2, money: 11.6, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/8/8d/Icon-crude-oil.png" },
  "Crushed Bauxite": { rp: 1, money: 75, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/a0/Icon-crushed-bauxite.png" },
  "Cut Oak Log": { rp: 1, money: 3.48, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/82/Icon-cut-oak-log.png" },
  "Deep Earth Fragment": { rp: 1, money: 200, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f0/Icon-deep-earth-fragment.png" },
  "Depleted UF6 Waste": { rp: 0, money: -250, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/b/bc/Icon-depleted-uf6-waste.png" },
  "Diesel": { rp: 2, money: 30.45, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/8/8f/Icon-diesel.png" },
  "Dirty Lithium Sulfate": { rp: 1, money: 60, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/d8/Icon-dirty-lithium-sulfate.png" },
  "Distilled Water": { rp: 0.3, money: 1, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/8/89/Icon-distilled-water.png" },
  "Dynamite": { rp: 25, money: 120, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f4/Icon-dynamite.png" },
  "Electric Motor": { rp: 200, money: 4500, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/a7/Icon-electric-motor.png" },
  "Electromagnet": { rp: 1, money: 950, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fe/Icon-electromagnet.png" },
  "Enriched UF6 Gas": { rp: 0, money: 150, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/78/Icon-enriched-uf6-gas.png" },
  "Enriched UO2 Pellets": { rp: 1, money: 256, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/ac/Icon-enriched-uo2-pellets.png" },
  "Ethanol": { rp: 2, money: 5.8, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/4/41/Icon-ethanol.png" },
  "Ethylene": { rp: 0.2, money: 14.5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/75/Icon-ethylene.png" },
  "Exhaust": { rp: 0, money: -0.5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/8/89/Icon-exhaust.png" },
  "Ferroalluminium Alloy Ingot": { rp: 1, money: 2500, type: "item", icon: "undefined" },
  "Ferroaluminium Magnet": { rp: 120, money: 8500, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/79/Icon-ferroaluminium-magnet.png" },
  "Filter": { rp: 1, money: 20, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/09/Icon-filter.png" },
  "Filtered Water": { rp: 0.2, money: 0.55, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/2/2d/Icon-filtered-water.png" },
  "Fission Byproducts": { rp: 0, money: -5000000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/08/Icon-fission-byproducts.png" },
  "Fracking Oil": { rp: 0.2, money: 1, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/2/2d/Icon-fracking-oil.png" },
  "Galvanized Steel": { rp: 33, money: 123, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/54/Icon-galvanized-steel.png" },
  "Gasoline": { rp: 7.5, money: 40.6, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/1/1b/Icon-gasoline.png" },
  "GasolineE10": { rp: 13, money: 57, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/e/e0/Icon-gasolinee10.png" },
  "Gear": { rp: 20, money: 98.6, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f6/Icon-gear.png" },
  "Gearbox": { rp: 50, money: 2552, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/94/Icon-gearbox.png" },
  "Glass": { rp: 14, money: 80, type: "item", icon: "http://static.wikitide.net/industrialistwiki/c/cb/Icon-glass.png" },
  "Gold Ingot": { rp: 70, money: 4250, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b1/Icon-gold-ingot.png" },
  "Gold Wire": { rp: 1, money: 200, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/41/Icon-gold-wire.png" },
  "Graphite-Iron Electrode": { rp: 1, money: 80, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b7/Icon-graphite-iron-electrode.png" },
  "Graphite-Zinc Electrode": { rp: 1, money: 60, type: "item", icon: "http://static.wikitide.net/industrialistwiki/3/36/Icon-graphite-zinc-electrode.png" },
  "Gravel": { rp: 0.1, money: 4, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/bf/Icon-gravel.png" },
  "Gunpowder": { rp: 1, money: 70, type: "item", icon: "http://static.wikitide.net/industrialistwiki/6/6f/Icon-gunpowder.png" },
  "Hardened Plastic Casing": { rp: 20, money: 200, type: "item", icon: "http://static.wikitide.net/industrialistwiki/c/c0/Icon-hardened-plastic-casing.png" },
  "Hardened Plastic Pellets": { rp: 10, money: 2.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/ef/Icon-hardened-plastic-pellets.png" },
  "Heavy Oil": { rp: 0.2, money: 5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/e/ef/Icon-heavy-oil.png" },
  "High Pressure Steam": { rp: 0, money: 0.03, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/c/c0/Icon-high-pressure-steam.png" },
  "Hot Crude Oil": { rp: 0, money: 0.14, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/3/38/Icon-hot-crude-oil.png" },
  "Hydrochloric Acid": { rp: 10, money: 80, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/6/64/Icon-hydrochloric-acid.png" },
  "Hydrofluoric Acid": { rp: 13, money: 600, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/9/98/Icon-hydrofluoric-acid.png" },
  "Hydrogen": { rp: 0.5, money: 0.02, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/e/e8/Icon-hydrogen.png" },
  "Hydrogen Sulfide": { rp: 0, money: 8, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/73/Icon-hydrogen-sulfide.png" },
  "Impure Boron": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/47/Icon-impure-boron.png" },
  "Insulated Wire": { rp: 1, money: 40, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/d9/Icon-insulated-wire.png" },
  "Iron Coil": { rp: 4, money: 43.85, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/99/Icon-iron-coil.png" },
  "Iron Drill Head": { rp: 30, money: 145000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/13/Icon-iron-drill-head.png" },
  "Iron Ingot": { rp: 1, money: 65.54, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/bd/Icon-iron-ingot.png" },
  "Iron Mix": { rp: 1, money: 10, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/1f/Icon-iron-mix.png" },
  "Iron Plate": { rp: 1, money: 70.18, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/75/Icon-iron-plate.png" },
  "Iron Plate 2": { rp: 1, money: 295.8, type: "item", icon: "undefined" },
  "Iron Powder": { rp: 1, money: 15, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b4/Icon-iron-powder.png" },
  "Lead Ingot": { rp: 1, money: 25, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/55/Icon-lead-ingot.png" },
  "Leaded Gasoline": { rp: 23, money: 112, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/2/2f/Icon-leaded-gasoline.png" },
  "Light Oil": { rp: 0.1, money: 7, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/6/69/Icon-light-oil.png" },
  "Limestone": { rp: 0.2, money: 1, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/71/Icon-limestone.png" },
  "Liquid Aluminium": { rp: 0, money: 200, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/a/a0/Icon-liquid-aluminium.png" },
  "Liquid Argon": { rp: 3, money: 50, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/f/fa/Icon-liquid-argon.png" },
  "Liquid Brass": { rp: 0, money: 30, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/a/a4/Icon-liquid-brass.png" },
  "Liquid Copper": { rp: 0, money: 7.54, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/c/cf/Icon-liquid-copper.png" },
  "Liquid Glass": { rp: 1, money: 10, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/4/45/Icon-liquid-glass.png" },
  "Liquid Gold": { rp: 0, money: 1000, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/c/cd/Icon-liquid-gold.png" },
  "Liquid Iron": { rp: 0, money: 23.2, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/b/b5/Icon-liquid-iron.png" },
  "Liquid Lead": { rp: 0, money: 5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/9/97/Icon-liquid-lead.png" },
  "Liquid Nitrogen": { rp: 3, money: 4, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/f/f8/Icon-liquid-nitrogen.png" },
  "Liquid Oxygen": { rp: 3, money: 6, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/5/57/Icon-liquid-oxygen.png" },
  "Liquid Sulfur": { rp: 0, money: 12, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/9/96/Icon-liquid-sulfur.png" },
  "Lithium Battery Pack": { rp: 180, money: 85000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/db/Icon-lithium-battery-pack.png" },
  "Lithium Brine": { rp: 1, money: 25, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/3/3b/Icon-lithium-brine.png" },
  "Lithium Carbonate": { rp: 40, money: 200, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/9f/Icon-lithium-carbonate.png" },
  "Lithium Ore": { rp: 1, money: 10, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/83/Icon-lithium-ore.png" },
  "Lithium Sulfate": { rp: 1, money: 100, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b3/Icon-lithium-sulfate.png" },
  "LNG": { rp: 2, money: 160, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/5/5e/Icon-lng.png" },
  "Logic Plate": { rp: 1, money: 65, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fa/Icon-logic-plate.png" },
  "Low Enrichment Fuel Rod": { rp: 1, money: 20000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/16/Icon-low-enrichment-fuel-rod.png" },
  "Low Pressure Steam": { rp: 0, money: 0.03, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/70/Icon-low-pressure-steam.png" },
  "Machine Oil": { rp: 4, money: 29, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/6/6b/Icon-machine-oil.png" },
  "Medium Earth Fragment": { rp: 1, money: 120, type: "item", icon: "http://static.wikitide.net/industrialistwiki/c/c8/Icon-medium-earth-fragment.png" },
  "MEG": { rp: 0.2, money: 2.9, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/6/68/Icon-meg.png" },
  "Microchip Scrap": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/78/Icon-microchip-scrap.png" },
  "Mixed Fissile Nitrates": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/11/Icon-mixed-fissile-nitrates.png" },
  "Mixed Fissile Oxides": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/73/Icon-mixed-fissile-oxides.png" },
  "Mixed Uranium Oxides": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fb/Icon-mixed-uranium-oxides.png" },
  "Molten Ferroaluminium Alloy": { rp: 1, money: 1100, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/70/Icon-molten-ferroaluminium-alloy.png" },
  "Molten Purple Gold": { rp: 1, money: 580, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/a/a7/Icon-molten-purple-gold.png" },
  "MOX Fuel Rod": { rp: 100, money: 1000000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/dc/Icon-mox-fuel-rod.png" },
  "Nails": { rp: 1, money: 2.9, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/95/Icon-nails.png" },
  "Naphtha": { rp: 0.1, money: 15.6, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/e/e5/Icon-naphtha.png" },
  "Nitrogen": { rp: 0, money: 0.15, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/78/Icon-nitrogen.png" },
  "Oak Log": { rp: 1, money: 5.8, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/ac/Icon-oak-log.png" },
  "Oil Bottle": { rp: 20, money: 208.8, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/ad/Icon-oil-bottle.png" },
  "Oxygen": { rp: 0.5, money: 0.1, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/c/c2/Icon-oxygen.png" },
  "Packed Present": { rp: 0, money: 300, type: "Item", icon: "http://static.wikitide.net/industrialistwiki/2/24/Icon-packed-present.png" },
  "Paper": { rp: 7, money: 14.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/3/3f/Icon-paper.png" },
  "Paraxylene": { rp: 0.2, money: 14.5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/0/06/Icon-paraxylene.png" },
  "Phosphorus Oxychloride": { rp: 0, money: 0, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/1/13/Icon-phosphorus-oxychloride.png" },
  "Plank 2": { rp: 1, money: 40.6, type: "item", icon: "undefined" },
  "Planks": { rp: 5, money: 13.05, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/83/Icon-planks.png" },
  "Plastic Bottle": { rp: 30, money: 72.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/2/2f/Icon-plastic-bottle.png" },
  "Plastic Casing": { rp: 7, money: 145, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/71/Icon-plastic-casing.png" },
  "Plastic Pellets": { rp: 25, money: 0.87, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/1d/Icon-plastic-pellets.png" },
  "Plutonium Oxide Pellets": { rp: 0, money: 1250, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/bc/Icon-plutonium-oxide-pellets.png" },
  "Poor Quality Diesel": { rp: 1.5, money: 21.75, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/d/d0/Icon-poor-quality-diesel.png" },
  "Powdered Tungsten": { rp: 1, money: 150, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/e1/Icon-powdered-tungsten.png" },
  "Powered Tungsten Carbide": { rp: 1, money: 210, type: "item", icon: "undefined" },
  "Present Box": { rp: 1, money: 174, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fe/Icon-present-box.png" },
  "PTA": { rp: 0.2, money: 2.9, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/1/1f/Icon-pta.png" },
  "Purple Gold Ingot": { rp: 100, money: 20000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/a6/Icon-purple-gold-ingot.png" },
  "Raw Copper": { rp: 1, money: 5.51, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/87/Icon-raw-copper.png" },
  "Raw Gas": { rp: 0, money: 0.03, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/d/d3/Icon-raw-gas.png" },
  "Raw Iron": { rp: 1, money: 5.8, type: "item", icon: "http://static.wikitide.net/industrialistwiki/c/c5/Icon-raw-iron.png" },
  "Raw Lead": { rp: 1, money: 10, type: "item", icon: "http://static.wikitide.net/industrialistwiki/a/af/Icon-raw-lead.png" },
  "Raw Uranium": { rp: 1, money: 54, type: "item", icon: "http://static.wikitide.net/industrialistwiki/b/b2/Icon-raw-uranium.png" },
  "Raw Zinc": { rp: 1, money: 5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/2/27/Icon-raw-zinc.png" },
  "Raw Zirconium": { rp: 1, money: 32, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f8/Icon-raw-zirconium.png" },
  "Rawmix": { rp: 1, money: 2, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/9f/Icon-rawmix.png" },
  "Refined Diesel": { rp: 3, money: 40.6, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/e/ea/Icon-refined-diesel.png" },
  "Refined Diesel Bottle": { rp: 15, money: 449.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/97/Icon-refined-diesel-bottle.png" },
  "Refined Gas": { rp: 0.01, money: 0.29, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/3/35/Icon-refined-gas.png" },
  "Reinforced Concrete Block": { rp: 4, money: 630, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/99/Icon-reinforced-concrete-block.png" },
  "Reprocessed Uranium": { rp: 1, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f5/Icon-reprocessed-uranium.png" },
  "Residue": { rp: 0, money: -5.8, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/7b/Icon-residue.png" },
  "Residue Bottle": { rp: 0, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/06/Icon-residue-bottle.png" },
  "Rich Soil": { rp: 1, money: 5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/fc/Icon-rich-soil.png" },
  "Rock": { rp: 1, money: 4, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/10/Icon-rock.png" },
  "Rubber": { rp: 90, money: 19.4, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/57/Icon-rubber.png" },
  "Sand": { rp: 0.1, money: 4, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f0/Icon-sand.png" },
  "Semiconductor": { rp: 30, money: 650, type: "item", icon: "http://static.wikitide.net/industrialistwiki/2/25/Icon-semiconductor.png" },
  "Shallow Earth Fragment": { rp: 1, money: 30, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/08/Icon-shallow-earth-fragment.png" },
  "SIlicon": { rp: 1, money: 50, type: "item", icon: "undefined" },
  "Slightly Enriched UF6 Gas": { rp: 0, money: 45, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/7f/Icon-slightly-enriched-uf6-gas.png" },
  "Sodium Carbonate": { rp: 1, money: 8, type: "item", icon: "http://static.wikitide.net/industrialistwiki/2/2f/Icon-sodium-carbonate.png" },
  "Sodium Hydroxide Solution": { rp: 1, money: 10, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/a/ad/Icon-sodium-hydroxide-solution.png" },
  "Soil": { rp: 0.1, money: 2, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/53/Icon-soil.png" },
  "Spent Fuel": { rp: 0, money: -1000000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/e6/Icon-spent-fuel.png" },
  "Spent Mox Fuel": { rp: 0, money: -1000000, type: "item", icon: "undefined" },
  "Standard Fuel Rod": { rp: 100, money: 150000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/0a/Icon-standard-fuel-rod.png" },
  "Steam": { rp: 0, money: 0.03, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/2/29/Icon-steam.png" },
  "Steel Coil": { rp: 1, money: 75, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/48/Icon-steel-coil.png" },
  "Steel Drill Head": { rp: 125, money: 190000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/75/Icon-steel-drill-head.png" },
  "Steel Ingot": { rp: 1, money: 48.72, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/54/Icon-steel-ingot.png" },
  "Steel Plate": { rp: 18, money: 89.9, type: "item", icon: "http://static.wikitide.net/industrialistwiki/6/6b/Icon-steel-plate.png" },
  "Steel Rod": { rp: 1, money: 92.8, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/df/Icon-steel-rod.png" },
  "Sulfur": { rp: 12, money: 30, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/d2/Icon-sulfur.png" },
  "Sulfur Dioxide": { rp: 0, money: 2, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/b/b6/Icon-sulfur-dioxide.png" },
  "Sulfur Trioxide": { rp: 0, money: 2.5, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/d/d8/Icon-sulfur-trioxide.png" },
  "Sulfuric Acid": { rp: 4, money: 65, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/a/a7/Icon-sulfuric-acid.png" },
  "Table Salt": { rp: 1, money: 4, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/7e/Icon-table-salt.png" },
  "Tetraethyllead": { rp: 7, money: 21, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/2/29/Icon-tetraethyllead.png" },
  "Tire": { rp: 40, money: 2000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/8d/Icon-tire.png" },
  "Tire Rim": { rp: 1, money: 1800, type: "item", icon: "http://static.wikitide.net/industrialistwiki/8/8c/Icon-tire-rim.png" },
  "Toy": { rp: 1, money: 101.5, type: "item", icon: "http://static.wikitide.net/industrialistwiki/6/68/Icon-toy.png" },
  "Treated Raw Copper": { rp: 1, money: 6, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/13/Icon-treated-raw-copper.png" },
  "Treated Raw Iron": { rp: 1, money: 8, type: "item", icon: "http://static.wikitide.net/industrialistwiki/d/d0/Icon-treated-raw-iron.png" },
  "Treated Rock": { rp: 1, money: 15, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/79/Icon-treated-rock.png" },
  "Tributyl Phosphate": { rp: 0, money: 0, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/7f/Icon-tributyl-phosphate.png" },
  "Tungsten Carbide Drill Head": { rp: 225, money: 800000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/0/03/Icon-tungsten-carbide-drill-head.png" },
  "Tungsten Carbide Plate": { rp: 70, money: 600, type: "item", icon: "http://static.wikitide.net/industrialistwiki/6/6a/Icon-tungsten-carbide-plate.png" },
  "Uncharged Lithium-Ion Battery": { rp: 1, money: 2000, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/e6/Icon-uncharged-lithium-ion-battery.png" },
  "Unenriched UF6 Gas": { rp: 0, money: 30, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/5/51/Icon-unenriched-uf6-gas.png" },
  "Water": { rp: 0, money: 0.23, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/5/5d/Icon-water.png" },
  "Water Bottle": { rp: 20, money: 174, type: "item", icon: "http://static.wikitide.net/industrialistwiki/e/ee/Icon-water-bottle.png" },
  "Water-Free Gas": { rp: 0, money: 0.14, type: "fluid", icon: "http://static.wikitide.net/industrialistwiki/7/76/Icon-water-free-gas.png" },
  "Wet Concrete": { rp: 1, money: 120, type: "item", icon: "http://static.wikitide.net/industrialistwiki/4/4b/Icon-wet-concrete.png" },
  "Yellowcake": { rp: 5, money: 0, type: "item", icon: "http://static.wikitide.net/industrialistwiki/2/2b/Icon-yellowcake.png" },
  "Zinc": { rp: 1, money: 20, type: "item", icon: "http://static.wikitide.net/industrialistwiki/1/12/Icon-zinc.png" },
  "Zinc Sulfate": { rp: 1, money: 10, type: "item", icon: "http://static.wikitide.net/industrialistwiki/f/f1/Icon-zinc-sulfate.png" },
  "Zirconium Chloride": { rp: 1, money: 30, type: "item", icon: "http://static.wikitide.net/industrialistwiki/9/9c/Icon-zirconium-chloride.png" },
  "Zirconium Dioxide": { rp: 1, money: 45, type: "item", icon: "http://static.wikitide.net/industrialistwiki/5/5a/Icon-zirconium-dioxide.png" },
  "Zirconium Rod": { rp: 1, money: 180, type: "item", icon: "http://static.wikitide.net/industrialistwiki/7/71/Icon-zirconium-rod.png" }
};

function createItemSelect(container, station, idx) {
    const select = document.createElement("select");

    items.forEach(it => {
        const option = document.createElement("option");
        option.value = it.name;
        option.textContent = it.name;
        option.dataset.icon = it.icon; // store icon url
        select.appendChild(option);
    });

    // initialize Choices.js
    const choice = new Choices(select, {
        searchEnabled: true,
        itemSelectText: '',
        callbackOnCreateTemplates: function(template) {
            return {
                option: (classNames, data) => {
                    return template(`
                        <div class="${classNames.item} ${data.highlighted ? classNames.highlightedState : classNames.itemSelectable}" data-select-text="${this.config.itemSelectText}" data-choice ${data.disabled ? 'data-choice-disabled aria-disabled="true"' : 'data-choice-selectable'}>
                            <img src="${data.customProperties.icon}" style="width:24px; margin-right:5px;">
                            ${data.label}
                        </div>
                    `);
                }
            };
        }
    });

    select.addEventListener("change", () => {
        station.items[idx] = select.value;
        recalcAll();
    });

    container.appendChild(select);
}
